runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: "production"
  PORT: "5000"
  MONGO_URI: "mongodb+srv://murtaza:ES89uhbkRyx7YbsU@stocksearch.trku8c1.mongodb.net/StockSearch"
  MONGODB_USERNAME: "murtazavasi2000"
  MONGODB_USER_PASSWORD: "ES89uhbkRyx7YbsU"
  FINNHUB_BASE_URL: "https://finnhub.io/api/v1"
  FINNHUB_API_KEY: "cmtbla9r01qqtangmrbgcmtbla9r01qqtangmrc0"
  POLYGON_BASE_URL: "https://api.polygon.io/v2"
  POLYGON_API_KEY: "BxdBEjis4HEw3hLPhUkkdFuzAQCvZXLU"
